---
title: 'Profiling: 3D'
author: "Xianbin Cheng"
date: "7/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objective

  * Use profiling to determine memory and time usage in one iteration
  
# Methods

1. Load libraries and source R code.

```{r, warning = FALSE, message = FALSE}
source(file = "Sampling_libraries.R")
source(file = "Sampling_contamination.R")
source(file = "Sampling_contamination_3d.R")
source(file = "Sampling_visualization.R")
source(file = "Sampling_assay_prep.R")
source(file = "Sampling_plan.R")
source(file = "Sampling_plan_3d.R")
source(file = "Sampling_assay_3d.R")
source(file = "Sampling_assay.R")
source(file = "Sampling_outcome_3d.R")
source(file = "Sampling_outcome.R")
source(file = "Sampling_iteration.R")
source(file = "Sampling_tuning_3d.R")
source(file = "Sampling_analysis.R")
library(profvis)
library(bench)
#library(proftools)
```

2. List important parameters.
        
```{r}
# Pre-generate healthy kernel concentrations to save time
conc_neg = rpert(n = 10^6, min = 0, mode = 0.7, max = 19.99, shape = 80)
```

```{r}
## Contamination
c_hat = 5
# x_lim = c(0, 3)
# y_lim = c(0, 2)
# z_lim = c(0, 1.5)
# lims = list(xlim = x_lim, ylim = y_lim, zlim = z_lim)

dis_level = make_dis_level(type = "constant", args = 40000)
# dis_level = make_dis_level(type = "Gamma", args = c(40000, 20))

spread = "discrete"
n_affected = 1
covar_mat = make_covar_mat(spread = spread, varx = 0.0004, vary = 0.0004, varz = 0.0004, 
                           covxy = 0, covxz = 0, covyz = 0)

# Sampling
method_sp = "srs"
n_sp = 1
n_strata = NA
by = NA
d = 0.04
sp_radius = d / 2
# L = z_lim[2]
m_kbar = 0.3 
rho = 1.28
homogeneity = 0.1

### SS
# L = get_Lprobe(container = container, lims = lims)

if(method_sp == "ss"){
  container = "truck"

  if(container == "hopper"){
    compartment = 2
    type = "open_top"
  } else {
    compartment = type = NULL
  }
} else if (method_sp %in% c("srs", "strs")) {
  container = type = compartment = NULL
}

# Assaying
method_det = "ELISA aflatoxin"
tox = "AF"
Mc = 20

# Iteration
# n_iter = 5
```

```{r, eval = FALSE}
# Run this if we want reproducibility
set.seed(123)
```

3. Profiling for different scenarios

  * Input parameters
    + `lims` = 1x1x1 or 2x1x1
    + `c_hat` = 1 or 10
    + `n_sp` = 1 or 10
    + `n_affected` = 1 or 10
    + `n_iter`x`n_seed` = 1 or 100
     
  * Check the `sim_outcome_new()`, `tune_param()`.

```{r, eval = FALSE}
# 1x1x1
x_lim = c(0, 1)
y_lim = c(0, 1)
z_lim = c(0, 1)
lims = list(xlim = x_lim, ylim = y_lim, zlim = z_lim)
L = z_lim[2]

ArgList_Ex1 = list(c_hat = c_hat, lims = lims, spread = spread, covar_mat = covar_mat,
                       n_affected = n_affected, dis_level = dis_level, method_sp = method_sp, 
                       sp_radius = sp_radius, n_sp = n_sp, n_strata = n_strata, by = by, L = L, 
                       rho = rho, m_kbar = m_kbar, conc_neg = conc_neg, tox = tox, Mc = Mc, 
                       method_det = method_det, verbose = FALSE, homogeneity = homogeneity, 
                       compartment = compartment, type = type, container = container)

profvis(expr = {tune_param(Args = ArgList_Ex1, n_seed = 1, n_iter = 1, param = "c_hat", val = 5)})

profvis(expr = {tune_param(Args = ArgList_Ex1, n_seed = 1, n_iter = 1, param = "c_hat", val = 50)})

profvis(expr = {tune_param(Args = ArgList_Ex1, n_seed = 1, n_iter = 1, param = "n_sp", val = 10)})

profvis(expr = {tune_param(Args = ArgList_Ex1, n_seed = 1, n_iter = 1, param = "n_affected", val = 10)})

profvis(expr = {tune_param(Args = ArgList_Ex1, n_seed = 10, n_iter = 10, param = "c_hat", val = 5)})
```

```{r, eval = FALSE}
# 2x1x1
x_lim = c(0, 2.5)
y_lim = c(0, 2)
z_lim = c(0, 2)
lims = list(xlim = x_lim, ylim = y_lim, zlim = z_lim)
L = z_lim[2]

ArgList_Ex2 = list(c_hat = c_hat, lims = lims, spread = spread, covar_mat = covar_mat,
                       n_affected = n_affected, dis_level = dis_level, method_sp = method_sp, 
                       sp_radius = sp_radius, n_sp = n_sp, n_strata = n_strata, by = by, L = L, 
                       rho = rho, m_kbar = m_kbar, conc_neg = conc_neg, tox = tox, Mc = Mc, 
                       method_det = method_det, verbose = FALSE, homogeneity = homogeneity, 
                       compartment = compartment, type = type, container = container)

profvis(expr = {tune_param(Args = ArgList_Ex2, n_seed = 1, n_iter = 1, param = "c_hat", val = 5)})

profvis(expr = {tune_param(Args = ArgList_Ex2, n_seed = 1, n_iter = 1, param = "c_hat", val = 50)})

profvis(expr = {tune_param(Args = ArgList_Ex2, n_seed = 1, n_iter = 1, param = "n_sp", val = 10)})

profvis(expr = {tune_param(Args = ArgList_Ex2, n_seed = 1, n_iter = 1, param = "n_affected", val = 10)})

profvis(expr = {tune_param(Args = ArgList_Ex2, n_seed = 10, n_iter = 10, param = "c_hat", val = 5)})
```