---
title: 'Test: Sensivitivity Analysis'
author: "Xianbin Cheng"
date: "January 28, 2019"
output: html_document
---
# Objective

* We want to conduct sensitivity analysis.

# Method

1. Load the libraries.

```{r, warning = FALSE, message = FALSE}
library(epiR)
library(sensitivity)
library(tidyverse)
```

2. Read in the simulation data.

  * `n_contam` = 1, 4, 8, 16, 40, 80
  * `n_sp` = 5, 10, 15, 20, 30, 60
  * `n_strata` = 5
  * `by` = row
  * `spread` = continuous
  * `case` = 10, 11, 13, 12, 14, 15
  * `spread_radius` = 0.2
  * `n_iter` = 100
  
```{r}
result = read.csv("sim_data_1to80_5to60_3_10to15.csv", header = TRUE, stringsAsFactors = FALSE)
str(result)
```

3. Compare the partial rank correlation coefficient and calcultate p-values.

```{r}
#epiR
df1 = result %>%
  select(param, method_sp, n_sp, P_det)

epi.prcc(dat = df1, sided.test = 2)
```

4. Visualize PRCC in a tornado plot with 95% confidence intervals.

```{r}
#sensitivity
df2 = result %>%
  select(param, method_sp, n_sp)

result2 = sensitivity::pcc(X = df2, y = result$P_det, rank = TRUE, nboot = 100, conf = 0.95)
result2

temp = rownames_to_column(df = result2$PRCC, var = "Parameter")

ggplot(data = temp) +
    geom_col(aes(x = Parameter, y = original), fill = "grey") +
  geom_errorbar(aes(x = Parameter, ymin = temp$`min. c.i.`, ymax = temp$`max. c.i.`, width = 0.4)) +
  scale_x_discrete(labels = c("Sampling strategy", "Sample size", "Prevalence")) +
  labs(y = "PRCC") +
  coord_flip() +
  theme_classic()
```

